const DB={get:(k,d=[])=>JSON.parse(localStorage.getItem(k)||JSON.stringify(d)),set:(k,v)=>localStorage.setItem(k,JSON.stringify(v))};
function seed(){if(!localStorage.getItem('faculty'))DB.set('faculty',[]);if(!localStorage.getItem('students'))DB.set('students',[]);if(!localStorage.getItem('marks'))DB.set('marks',[]);if(!localStorage.getItem('attendance'))DB.set('attendance',[]);if(!localStorage.getItem('announcements'))DB.set('announcements',[{title:'Welcome to Student Web Portal',text:'Semester activities and academic updates will appear here.',date:'2026-10-03'}]);}
seed();
function login(e){e.preventDefault();const role=document.querySelector('#role').value,id=document.querySelector('#userId').value.trim(),pw=document.querySelector('#password').value;let ok=false;if(role==='admin')ok=id==='admin'&&pw==='admin123';if(role==='faculty')ok=DB.get('faculty').some(x=>x.id===id&&x.password===pw);if(role==='student')ok=DB.get('students').some(x=>x.id===id&&x.password===pw);if(!ok){document.querySelector('#msg').textContent='Invalid credentials. Please check role, ID and password.';return;}sessionStorage.setItem('role',role);sessionStorage.setItem('userId',id);location.href=role+'/dashboard.html';}
function guard(role){if(sessionStorage.getItem('role')!==role){location.href='../index.html';}}
function logout(){sessionStorage.clear();location.href='../index.html'}
function addStudent(e){e.preventDefault();let s=DB.get('students'),id=val('sid');if(s.some(x=>x.id===id)){alert('Student ID already exists');return;}let pass=val('password')||('Stu@'+id.slice(-5));let x={id,name:val('name'),dob:val('dob'),gender:val('gender'),email:val('email'),phone:val('phone'),address:val('address'),course:val('course'),dept:val('dept'),year:val('year'),semester:val('semester'),section:val('section'),admission:val('admission'),password:pass};s.push(x);DB.set('students',s);let box=document.querySelector('#success');box.style.display='block';box.innerHTML=`<b>✓ Student allocated successfully</b><br>Name: ${x.name}<br>Student ID / Username: ${x.id}<br>Department: ${x.dept} · Section: ${x.section}<br>Temporary Password: <b>${x.password}</b>`;e.target.reset();renderStudents();}
function val(id){return document.getElementById(id)?.value||''}
function renderStudents(){let el=document.querySelector('#studentRows');if(!el)return;el.innerHTML=DB.get('students').map(s=>`<tr><td>${s.id}</td><td>${s.name}</td><td>${s.dept}</td><td>${s.semester}</td><td>${s.section}</td><td><button class="btn danger" onclick="deleteStudent('${s.id}')">Delete</button></td></tr>`).join('')||'<tr><td colspan="6">No students</td></tr>';}
function deleteStudent(id){if(!confirm('Delete this student?'))return;DB.set('students',DB.get('students').filter(x=>x.id!==id));renderStudents();}
function addFaculty(e){e.preventDefault();let f=DB.get('faculty'),id=val('fid');if(f.some(x=>x.id===id)){alert('Faculty ID exists');return;}f.push({id,name:val('fname'),dept:val('fdept'),subject:val('fsubject'),password:val('fpassword')});DB.set('faculty',f);e.target.reset();renderFaculty();}
function renderFaculty(){let el=document.querySelector('#facultyRows');if(!el)return;el.innerHTML=DB.get('faculty').map(f=>`<tr><td>${f.id}</td><td>${f.name}</td><td>${f.dept}</td><td>${f.subject}</td></tr>`).join('');}
function addMark(e){e.preventDefault();let m=DB.get('marks');m.push({studentId:val('markStudent'),subject:val('subject'),exam:val('exam'),marks:Number(val('marks')),max:Number(val('max'))});DB.set('marks',m);alert('Marks saved');e.target.reset();}
function addAttendance(e){e.preventDefault();let a=DB.get('attendance');a.push({studentId:val('attStudent'),subject:val('attSubject'),present:Number(val('present')),total:Number(val('total'))});DB.set('attendance',a);alert('Attendance saved');e.target.reset();}
function fillStudentSelects(){document.querySelectorAll('.student-select').forEach(el=>el.innerHTML='<option value="">Select student</option>'+DB.get('students').map(s=>`<option value="${s.id}">${s.id} - ${s.name}</option>`).join(''));}
function adminStats(){let s=document.querySelector('#countStudents'),f=document.querySelector('#countFaculty');if(s)s.textContent=DB.get('students').length;if(f)f.textContent=DB.get('faculty').length;}
function studentHome(){let id=sessionStorage.getItem('userId'),s=DB.get('students').find(x=>x.id===id);if(!s)return;document.querySelectorAll('[data-student-name]').forEach(x=>x.textContent=s.name);let p=document.querySelector('#profile');if(p)p.innerHTML=`<tr><th>Student ID</th><td>${s.id}</td></tr><tr><th>Name</th><td>${s.name}</td></tr><tr><th>Course</th><td>${s.course}</td></tr><tr><th>Department</th><td>${s.dept}</td></tr><tr><th>Year / Semester</th><td>${s.year} / ${s.semester}</td></tr><tr><th>Section</th><td>${s.section}</td></tr><tr><th>Email</th><td>${s.email||'-'}</td></tr>`;let mr=document.querySelector('#myMarks');if(mr)mr.innerHTML=DB.get('marks').filter(x=>x.studentId===id).map(x=>`<tr><td>${x.subject}</td><td>${x.exam}</td><td>${x.marks}/${x.max}</td><td>${x.marks/x.max>=.4?'Pass':'Needs Improvement'}</td></tr>`).join('');let ar=document.querySelector('#myAttendance');if(ar)ar.innerHTML=DB.get('attendance').filter(x=>x.studentId===id).map(x=>`<tr><td>${x.subject}</td><td>${x.present}</td><td>${x.total}</td><td>${Math.round(x.present/x.total*100)}%</td></tr>`).join('');}
function announcements(){let el=document.querySelector('#announcements');if(el)el.innerHTML=DB.get('announcements').map(a=>`<div class="notice"><b>${a.title}</b><div class="hint">${a.date}</div><p>${a.text}</p></div>`).join('');}
document.addEventListener('DOMContentLoaded',()=>{renderStudents();renderFaculty();fillStudentSelects();adminStats();studentHome();announcements();});
